stages:
    - build
    - publish

builder:
    stage: build
    artifacts:
        untracked: true
        expire_in: 1hr
    script:
        - npm ci
        - npm run build

publish:
    dependencies:
        - builder
    stage: publish
    script:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
        - npm publish --access public
    only:
        - master
