stages:
    - publish

publish:
    stage: publish
    script:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
        - npm install
        - npm run build
        - npm publish --access public
    only:
        - master
