stages:
    - build
    - publish

cache:
    paths:
        - dist

builder:
    stage: build
    script:
        - npm ci
        - npm run build

publish:
    dependencies:
        - builder
    stage: publish
    script:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
        - npm publish --access public
    only:
        - master
